# Generated by Django 5.2.3 on 2025-06-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='style',
            field=models.CharField(blank=True, default='badiy', max_length=250, null=True),
        ),
    ]
