# Generated by Django 5.2.3 on 2025-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_article_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('nasriy', 'Nasriy'), ('sheriy', 'She’riy')], default='nasriy', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.CharField(blank=True, choices=[('badiiy', 'Badiiy uslub'), ('ilmiy', 'Ilmiy uslub'), ('publitsistik', 'Publitsistik uslub'), ('rasmiy', 'Rasmiy uslub')], default='badiiy', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
