# Generated by Django 5.2.3 on 2025-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_article_genre_article_pub_year_article_word_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, choices=[('nasriy', 'Nasriy'), ('sheriy', 'She’riy')], default='nasriy', max_length=10),
        ),
    ]
