# Generated by Django 5.2.3 on 2025-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_alter_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, choices=[('nasriy', 'Nasriy'), ("she'riy", 'She’riy'), ('ilmiy', 'Ilmiy'), ('publitsistik', 'Publitsistik'), ('rasmiy', 'Rasmiy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
