# Generated by Django 5.2.3 on 2025-07-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_alter_article_genre_alter_article_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, choices=[('nasriy', 'Nasriy'), ('sheriy', 'She’riy'), ('ilmiy', 'Ilmiy'), ('publitsistik', 'Publitsistik'), ('rasmiy', 'Rasmiy')], max_length=20, null=True),
        ),
    ]
